name: Update Energy Providers JSON

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC

jobs:
  update-energyproviders-json:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    # Run the new script
    - name: Run Script to Update energyproviders.json
      run: |
        python update_energyproviders_from_excel.py

    # Commit and push changes
    - name: Commit and Push Changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add energyproviders.json
        git diff --cached --quiet || git commit -m "Update energyproviders.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
